vich_uploader:
    db_driver: orm

    mappings:
        featured_images:
            uri_prefix: '%app.path.images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.images%'
